### ISSUE TITLE
Missing “withdrawal for fees” asset tx in onchain reserve

### ISSUE THREAD

**Issue by hieronx** [centrifuge/pools-subql#233]
Fees were paid onchain on July 11th (https://centrifuge.subscan.io/extrinsic/5870442-2?event=5870442-20) and July 25th (https://centrifuge.subscan.io/extrinsic/5964743-2?event=5964743-15).

There is only 1 `Withdrawal for fees` asset transaction, on July 25th. See https://app.centrifuge.io/#/pools/4139607887/assets/0

**Comment by filo87** [comment]
@hieronx  Looks they are not missing, but they get registered one epoch later. This is due to the order in which the events are processed.

Paid Fees are currentlty accumulated on the epoch entity on the property  `sumPoolFeesPaidAmount` and upon epoch execution, te accumulated amount is posted to a `WITHDRAWAL_FOR_FEES` Asset Transaction.

as can be seen here:

![Image](https://github.com/user-attachments/assets/017220c6-2cc9-4785-b9ea-928e2eb03dc6)

As the `EpochClosed` event fires right before the `Paid` event for pool fees, these are first logged on the closing of the next Epoch

![Image](https://github.com/user-attachments/assets/e37abf82-c8f2-4399-b244-e737451386c2)

This is reflected also in the totals, in fact the logged AssetTransaction on July 25th:



![Image](https://github.com/user-attachments/assets/0de829ca-9eb6-4bda-b6cd-707ee1d6d1b6)


 corresponds to the sum of fees actually paid on July 11:

![Image](https://github.com/user-attachments/assets/1d48dcef-77b8-4a07-8e5a-c94d80df10bb)


Thus: 1859801476*2 = 3'719'602'952

This means that the other will be accounted when the next epoch is closed.

If this is a problem, than we should change fundamentally how fees are logged.

**Comment by hieronx** [comment]
Thanks for the digging!

> As the EpochClosed event fires right before the Paid event for pool fees, these are first logged on the closing of the next Epoch

This part I don't fully understand though. The order should be (afaik):
- `poolSystem.EpochClosed`
- `poolFees.Paid`
- `poolSystem.EpochExecuted`

It is epoch execution, not closing, upon which we should create the `withdrawal for fees` asset tx. That should be after the `Paid` events, not before. The closing of epoch should not really matter for this.

**Comment by filo87** [comment]
I think I have a fix...it depends on whether fees are paid between epochClosed and epochExecuted or after epochExecuted.

This because upon epoch closure the currentEpoch counter on the pool is increased. This leads to the fees being incremented in the next one.

So by handling the cases pool.lastEpochClosed === pool.lastEpochExecuted or vice versa it should work....
